#!/bin/bash
TORRENT_ID=$1
TORRENT_NAME=$2
TORRENT_PATH=$3
filebot -script fn:amc --output "/download" --action move --conflict skip -non-strict --def subtitles=en artwork=n backdrops=n music=n xbmc=localhost plex=localhost deleteAfterExtract=y clean=y "seriesFormat=TV Shows/{n}/Season {s}/{n} {sxe} {t}" "ut_dir=$TORRENT_PATH/$TORRENT_NAME" "ut_kind=multi" "ut_title=$TORRENT_NAME"
